// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azzxusfzwhskgoioikmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6enh1c2Z6d2hza2dvaW9pa210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODYxNjksImV4cCI6MjA2OTU2MjE2OX0.YkEwpRqGD39H_EkT5V3b7YoOdGGf7HXuAgjnYhV9mx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});